spring:
  application:
    name: ms-notification

  kafka:
    bootstrap-servers: ${KAFKA_SERVER_1:localhost:9091},${KAFKA_SERVER_2:localhost:9093},${KAFKA_SERVER_3:localhost:9094}
    consumer:
      group-id: ${KAFKA_GROUP_ID:CASINHA}


  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 4

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_NAME:kainanytbr@gmail.com}
    password: ${MAIL_PASSWORD:cnay urni vavv qxas}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: 0

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVICE_URL:localhost:8761}/eureka/


