spring:
  application:
    name: ms-notification

  kafka:
    bootstrap-servers: http://172.20.0.3:9092,http://172.20.0.4:9092,http://172.20.0.2:9092
    consumer:
      group-id: ${KAFKA_GROUP_ID:CASINHA}

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_NAME:kainanytbr@gmail.com}
    password: ${MAIL_PASSWORD:cnay urni vavv qxas}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: 0

eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://172.20.0.4:8761/eureka/


